source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do 

pod 'SDWebImage', '>= 5.0.0'  
pod "MWPhotoBrowser", :git => 'https://github.com/yifan513/MWPhotoBrowser.git'
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :git => 'https://github.com/yifan513/MWPhotoBrowser.git' 
pod 'SDWebImage', '>= 5.0.0'
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
